apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: backend
  name: csgo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend 
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
      - image: manfromth3m0on/csgo 
        imagePullPolicy: IfNotPresent
        name: csgo
